app01/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from app01 import views

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    # 位置参数：新闻查看/新闻类别/第几页
    url(r'^show_news/(\d+)/(\d+)$', views.show_news, name='show_news'),
    # 关键字参数：新闻查看/新闻类别/第几页
    url(r'^show_news2/(?P<category>\d+)/(?P<page_no>\d+)$',
        views.show_news2, name='show_news2'),

    url(r'^index1$', views.index1),

    url(r'^inherit', views.inherit, name='inherit'),
    url(r'^create_verify_code$', views.create_verify_code),
    url(r'^show_verify_codele$', views.show_verify_codele),
    url(r'^do_verify_codele$', views.do_verify_codele),
]

djang04/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app01.urls', namespace='app01')),
]

app01/models.py
from django.db import models

# Create your models here.

app01/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.utils.timezone import now
from PIL import Image, ImageDraw, ImageFont
from django.utils.six import BytesIO

# def index(request):
#     contxet ={}   #字典
#     # 获取模板对象
#     template = loader.get_template('index.html')
#     # 渲染模板对象
#     html_str = contxet = template.render(contxet, request)
#     return HttpResponse(html_str)
# # from django.template.defaulttags import now


class Student(object):
    # name = 'Tom'
    def name(self):
        return 'name'


def index(request):
    my_dict = {'key01': 'value01', 'key02': 'value01'}
    my_list = ['列表01', '列表02', '列表03', '列表04']
    my_obj = Student()
    my_date = now()

    context = {
        'number': 5,
        'my_dict': my_dict,
        'my_list': my_list,
        'my_obj': my_obj,
        'my_date': my_date,
          }
    return render(request, 'index.html', context)


def index1(request):
    my_html = '<font color="red">红色</font>'
    context = {
        'my_html': my_html
          }
    return render(request, 'index.html', context)


def inherit(request):

    return render(request, 'child.html')


def show_news(request, a, b):
    return HttpResponse("新闻界面：%s %s" % (a, b))


def show_news2(request, category, page_no):
    return HttpResponse("新闻界面2：%s %s" % (category, page_no))


def create_verify_code(request):
    """使用Pillow包生成验证码图片"""

    # 引入随机函数模块
    import random
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100),
               random.randrange(20, 100), 255)  # RGB

    width = 100
    height = 25
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)

    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)

    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'

    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]

    # 构造字体对象，ubuntu的字体路径为“/usr/share/fonts/truetype/freefont”
    font = ImageFont.truetype('FreeMono.ttf', 23)
    # 构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))

    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)

    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    # 内存文件操作
    buf = BytesIO()
    # 将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


def show_verify_codele(request):
    return render(request, 'show__verify_code.html')


def do_verify_codele(request):
    # 获取客户填写的验证码
    code = request.POST.get('verify_code')

    # 获取图片session填写的验证码
    code1 = request.session.get('verifycode')
    if code.upper()== code1.upper():
        return HttpResponse('验证通过')
    else:
        return HttpResponse('验证不通过')

templates/child.html
{% extends 'parent.html' %}
{% block title %}
<h3>子模板title </h3>
{% endblock %}

{% block header %}
    {{ block.super }}
<h3>子模板 头部</h3>
{% endblock %}

{% block footer %}
    {{ block.super }}
<h3>子模板 尾部</h3>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#    <h3>模板变量不为空</h3>#}
{#    数字:{{ number }}<br>#}
{#    字典：{{ my_dict.key01}}<br>#}
{#    列表：{{ my_list.1 }}<br>#}
{#    对象：{{ my_obj.name }}<br>#}
{#    <h1>使用for 遍历列表</h1>#}
{#    reversed 倒序遍历：#}
{#    {% for item in my_list reversed %}#}
{#        {{ item }}<br>#}
{#    {% empty %}#}
{#        列表为空#}
{#    {% endfor %}#}
{#    <h1>for 遍历字典</h1>#}
{#    {% for key,value in my_dict.items%}#}
{#        {{ forloop.counter }}  {{key}}:{{value}}<br/>#}
{#    {% endfor %}#}
{##}
{#    <h1>for forlooper.counter</h1>#}
{#    {% for item in my_list %}#}
{#        {{ forloop.counter }}  {{ item }}<br>#}
{#    {% endfor %}#}
{##}
{#    <h3>if</h3>#}
{#        {% if number == 1 %}#}
{#            1#}
{#        {% elif number == 5 %}#}
{#            5#}
{#        {% else %}#}
{#            其他#}
{#        {% endif %}#}
{##}
{#    <h3>if 逻辑运算</h3>#}
{#    {% if number >= 1 and number <= 10 %}#}
{#    1<={{ number }}<=10 成立#}
{#    {% else %}#}
{#        1<={{ number }}<=10 不成立#}
{#    {% endif %}#}
{##}
{#<h3>过滤器使用</h3>#}
{#列表长度：{{ my_list|length }}<br>#}
{#字典长度：{{ my_dict|length }}<br>#}
{#对象长度：{{ my_obj.name|length }}<br>#}
{##}
{#<h3>过滤器使用default</h3>#}
{#number：{{ number }}<br>#}
{#设置默认值：{{ number|default:10}}<br>#}
{#设置默认值：{{ number2|default:20}}<br>#}

{% comment %}
  注释内容
{% endcomment %}

{#<h3>过滤器使用date</h3>#}
{##}
{#设置默认值：{{my_date}}<br>#}
{#设置默认值：{{my_date|date:'Y年m月d日 H时i分s秒' }}<br>#}
{##}
{#<h3>自定义过滤器的使用date</h3>#}
{#{% load filters %}#}
{#{% if number|odd  %}#}
{#            奇数#}
{#{% else %}#}
{#    偶数#}
{#{% endif %}#}
{#<h3>通过render传给模板字典数据会发生转译</h3>#}
{#通过safe防止转译#}
{#{{my_html|safe }}#}
{#{% autoescape off %}#}
{#    {{ my_html }}    {{ my_html }}    {{ my_html }}#}
{#{% endautoescape %}#}
硬编码: <br/>
<a href="/inherit">进入首页</a> <br>
<a href="/show_news/1/2">进入新闻</a> <br>
<a href="/show_news2/1/2">进入新闻2</a> <br>
自动生成编码: <br/>
<a href="{% url 'app01:inherit'%}">进入首页</a> <br>
<a href="{% url 'app01:show_news' 0 0 %}">进入新闻</a> <br>
<a href="{% url 'app01:show_news2' category=1 page_no=2 %}">进入新闻2</a> <br>
<a href="{% url 'app01:show_news2' 0 0 %}">进入新闻2</a> <br>

</body>
</html>

templates/parent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>parent</title>
    {% block title %}
    父模板
    {% endblock %}
</head>
<body>
{% block header %}
    父模板头部
{% endblock header%}
<br>
<br>
<br>
<br>
{% block footer %}
父模板尾部
{% endblock %}

</body>
</html>

templates/show__verify_code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>show_verify_codele</title>
</head>
<body>
<form method="post" action="/do_verify_codele">

        {% csrf_token %}


        <input type="text" name="verify_code">
        <img src="/create_verify_code"> <br/>
        <input type="submit" value="提交">
    </form>

</body>
</html>